name: CoreRestAssured CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://reqres.in
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn -version

      - name: Build with Maven
        run: |
          echo "Running tests with BASE_URL: $BASE_URL"
          mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml -DBASE_URL=${BASE_URL} -Dmaven.test.failure.ignore=true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

