name: CoreRestAssured CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://reqres.in

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn -version

      - name: Verify TestNG configuration file exists
        run: |
          echo "Checking for TestNG configuration files..."
          ls -la testng.xml || echo "Root testng.xml not found"
          ls -la src/test/resources/testng.xml || echo "src/test/resources/testng.xml not found"
          echo "Project structure:"
          find . -name "*.xml" -type f | grep -E "(testng|pom)" | head -10

      - name: Build with Maven
        run: |
          echo "Building and running tests..."
          mvn clean compile test-compile
          echo "Running tests with specific TestNG suite..."
          mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml

      - name: Generate Allure Report
        if: always()
        run: |
          echo "Generating Allure report..."
          mvn allure:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/allure-results/

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            target/
            *.log

