name: CoreRestAssured CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://reqres.in

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml -DBASE_URL=${BASE_URL}

